export default function Head() {
  return (
		<>
			<title>Space Tourism </title>
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/assets/favicon-32x32.png" />
		</>
	);
}
